import type { LexiconItem, MoodTag } from "@emotion-journey/domain";

export const THEME_COLORS = {
  background: "#F6F3EA",
  foreground: "#1F2937",
  accent: "#7BC4F2",
  positive: "#F6C94A",
  negative: "#9AB0A6",
  success: "#22C55E",
  warning: "#F59E0B",
  danger: "#EF4444",
} as const;

export const APP_NAME = "Emotion Journey";

export const DEFAULT_MOOD_TAGS: MoodTag[] = [
  "焦虑",
  "成就感",
  "空虚",
  "紧绷",
  "开心",
  "平静",
  "疲惫",
  "沮丧",
];

export const DEFAULT_LEXICON: LexiconItem[] = [
  { keyword: "汇报", tags: ["紧绷", "成就感"], triggerKey: "工作任务", scoreBias: 1 },
  { keyword: "项目", tags: ["紧绷"], triggerKey: "工作任务", scoreBias: -1 },
  { keyword: "加班", tags: ["疲惫", "焦虑"], triggerKey: "工作任务", scoreBias: -2 },
  { keyword: "赶工", tags: ["疲惫", "紧绷"], triggerKey: "工作任务", scoreBias: -2 },
  { keyword: "开会", tags: ["紧绷"], triggerKey: "工作任务", scoreBias: -1 },
  { keyword: "绩效", tags: ["焦虑", "紧绷"], triggerKey: "工作任务", scoreBias: -2 },
  { keyword: "升职", tags: ["成就感", "开心"], triggerKey: "工作任务", scoreBias: 3 },
  { keyword: "被表扬", tags: ["开心", "成就感"], triggerKey: "工作任务", scoreBias: 3 },
  { keyword: "考试", tags: ["焦虑", "紧绷"], triggerKey: "学业压力", scoreBias: -2 },
  { keyword: "作业", tags: ["紧绷"], triggerKey: "学业压力", scoreBias: -1 },
  { keyword: "论文", tags: ["焦虑", "紧绷"], triggerKey: "学业压力", scoreBias: -2 },
  { keyword: "答辩", tags: ["焦虑", "紧绷"], triggerKey: "学业压力", scoreBias: -2 },
  { keyword: "录取", tags: ["开心", "成就感"], triggerKey: "学业压力", scoreBias: 3 },
  { keyword: "运动", tags: ["平静", "开心"], triggerKey: "身体活动", scoreBias: 2 },
  { keyword: "跑步", tags: ["平静", "开心"], triggerKey: "身体活动", scoreBias: 2 },
  { keyword: "散步", tags: ["平静"], triggerKey: "身体活动", scoreBias: 1 },
  { keyword: "健身", tags: ["成就感", "开心"], triggerKey: "身体活动", scoreBias: 2 },
  { keyword: "拉伸", tags: ["平静"], triggerKey: "身体活动", scoreBias: 1 },
  { keyword: "朋友", tags: ["开心"], triggerKey: "社交互动", scoreBias: 1 },
  { keyword: "聚会", tags: ["开心"], triggerKey: "社交互动", scoreBias: 2 },
  { keyword: "聊天", tags: ["平静"], triggerKey: "社交互动", scoreBias: 1 },
  { keyword: "陪伴", tags: ["平静", "开心"], triggerKey: "社交互动", scoreBias: 2 },
  { keyword: "被理解", tags: ["开心", "平静"], triggerKey: "社交互动", scoreBias: 2 },
  { keyword: "争吵", tags: ["沮丧", "焦虑"], triggerKey: "人际冲突", scoreBias: -3 },
  { keyword: "冷战", tags: ["空虚", "沮丧"], triggerKey: "人际冲突", scoreBias: -3 },
  { keyword: "误解", tags: ["焦虑", "沮丧"], triggerKey: "人际冲突", scoreBias: -2 },
  { keyword: "冲突", tags: ["焦虑", "沮丧"], triggerKey: "人际冲突", scoreBias: -2 },
  { keyword: "失眠", tags: ["疲惫", "空虚"], triggerKey: "睡眠问题", scoreBias: -2 },
  { keyword: "熬夜", tags: ["疲惫"], triggerKey: "睡眠问题", scoreBias: -2 },
  { keyword: "睡不着", tags: ["焦虑", "疲惫"], triggerKey: "睡眠问题", scoreBias: -2 },
  { keyword: "早醒", tags: ["疲惫"], triggerKey: "睡眠问题", scoreBias: -1 },
  { keyword: "睡过头", tags: ["空虚", "疲惫"], triggerKey: "睡眠问题", scoreBias: -1 },
  { keyword: "完成", tags: ["成就感", "开心"], triggerKey: "任务完成", scoreBias: 2 },
  { keyword: "搞定", tags: ["成就感", "开心"], triggerKey: "任务完成", scoreBias: 2 },
  { keyword: "收尾", tags: ["平静", "成就感"], triggerKey: "任务完成", scoreBias: 1 },
  { keyword: "突破", tags: ["成就感", "开心"], triggerKey: "任务完成", scoreBias: 3 },
  { keyword: "拖延", tags: ["空虚", "焦虑"], triggerKey: "时间管理", scoreBias: -2 },
  { keyword: "来不及", tags: ["焦虑", "紧绷"], triggerKey: "时间管理", scoreBias: -2 },
  { keyword: "排队", tags: ["疲惫"], triggerKey: "时间管理", scoreBias: -1 },
  { keyword: "通勤", tags: ["疲惫"], triggerKey: "出行", scoreBias: -1 },
  { keyword: "堵车", tags: ["焦虑", "疲惫"], triggerKey: "出行", scoreBias: -2 },
  { keyword: "晚点", tags: ["焦虑", "疲惫"], triggerKey: "出行", scoreBias: -1 },
  { keyword: "旅行", tags: ["开心"], triggerKey: "出行", scoreBias: 2 },
  { keyword: "回家", tags: ["平静"], triggerKey: "家庭关系", scoreBias: 1 },
  { keyword: "家人", tags: ["平静"], triggerKey: "家庭关系", scoreBias: 1 },
  { keyword: "父母", tags: ["紧绷"], triggerKey: "家庭关系", scoreBias: -1 },
  { keyword: "孩子", tags: ["开心", "紧绷"], triggerKey: "家庭关系", scoreBias: 0 },
  { keyword: "伴侣", tags: ["平静"], triggerKey: "家庭关系", scoreBias: 1 },
  { keyword: "房租", tags: ["焦虑", "紧绷"], triggerKey: "财务压力", scoreBias: -2 },
  { keyword: "还款", tags: ["焦虑"], triggerKey: "财务压力", scoreBias: -2 },
  { keyword: "工资", tags: ["成就感"], triggerKey: "财务压力", scoreBias: 1 },
  { keyword: "涨薪", tags: ["开心", "成就感"], triggerKey: "财务压力", scoreBias: 3 },
  { keyword: "生病", tags: ["焦虑", "疲惫"], triggerKey: "健康状态", scoreBias: -2 },
  { keyword: "头疼", tags: ["疲惫"], triggerKey: "健康状态", scoreBias: -1 },
  { keyword: "发烧", tags: ["疲惫", "焦虑"], triggerKey: "健康状态", scoreBias: -2 },
  { keyword: "康复", tags: ["平静", "开心"], triggerKey: "健康状态", scoreBias: 2 },
  { keyword: "通知", tags: ["紧绷"], triggerKey: "信息负荷", scoreBias: -1 },
  { keyword: "刷短视频", tags: ["空虚"], triggerKey: "数字过载", scoreBias: -1 },
  { keyword: "刷手机", tags: ["空虚"], triggerKey: "数字过载", scoreBias: -1 },
  { keyword: "消息轰炸", tags: ["焦虑", "紧绷"], triggerKey: "数字过载", scoreBias: -2 },
  { keyword: "断网", tags: ["焦虑"], triggerKey: "数字过载", scoreBias: -1 },
  { keyword: "冥想", tags: ["平静"], triggerKey: "情绪调节", scoreBias: 2 },
  { keyword: "写日记", tags: ["平静"], triggerKey: "情绪调节", scoreBias: 1 },
  { keyword: "听歌", tags: ["平静", "开心"], triggerKey: "娱乐恢复", scoreBias: 1 },
  { keyword: "电影", tags: ["开心"], triggerKey: "娱乐恢复", scoreBias: 1 },
  { keyword: "游戏", tags: ["开心"], triggerKey: "娱乐恢复", scoreBias: 1 },
  { keyword: "放空", tags: ["平静"], triggerKey: "娱乐恢复", scoreBias: 1 },
  { keyword: "下雨", tags: ["空虚"], triggerKey: "天气变化", scoreBias: -1 },
  { keyword: "晴天", tags: ["开心"], triggerKey: "天气变化", scoreBias: 1 },
  { keyword: "噪音", tags: ["紧绷"], triggerKey: "环境噪音", scoreBias: -1 },
  { keyword: "吵", tags: ["紧绷"], triggerKey: "环境噪音", scoreBias: -1 },
  { keyword: "安静", tags: ["平静"], triggerKey: "环境噪音", scoreBias: 1 },
  { keyword: "面试", tags: ["焦虑", "紧绷"], triggerKey: "求职压力", scoreBias: -2 },
  { keyword: "offer", tags: ["开心", "成就感"], triggerKey: "求职压力", scoreBias: 3 },
  { keyword: "被拒", tags: ["沮丧", "空虚"], triggerKey: "求职压力", scoreBias: -3 },
  { keyword: "学习", tags: ["平静", "成就感"], triggerKey: "自我成长", scoreBias: 1 },
  { keyword: "读书", tags: ["平静"], triggerKey: "自我成长", scoreBias: 1 },
  { keyword: "复盘", tags: ["成就感", "平静"], triggerKey: "自我成长", scoreBias: 1 },
  { keyword: "进步", tags: ["开心", "成就感"], triggerKey: "自我成长", scoreBias: 2 },
];

export const DEFAULT_RISK_TERMS = [
  "不想活",
  "伤害自己",
  "绝望",
  "撑不住",
  "自残",
  "轻生",
  "活不下去",
  "不如死了",
  "没必要活着",
  "想结束自己",
  "结束生命",
  "不想再醒来",
  "跳楼",
  "割腕",
  "吞药",
  "服药过量",
  "上吊",
  "离开这个世界",
  "想消失",
  "世界没有我更好",
  "我没有价值",
  "我一无是处",
  "没人需要我",
  "被世界抛弃",
  "彻底崩溃",
  "濒临崩溃",
  "失控",
  "控制不住自己",
  "伤害别人",
  "报复社会",
  "想杀人",
  "想同归于尽",
  "想毁掉一切",
  "不想面对明天",
  "想逃离一切",
  "不配活着",
  "结束吧",
  "再也撑不下去了",
  "完全没有希望",
  "活着没有意义",
  "suicide",
  "kill myself",
  "self harm",
  "want to die",
];

export const SAFETY_HINT =
  "你值得被认真对待。如果你正在经历强烈痛苦，请优先联系可信的人或当地专业支持热线。";

export const SUMMARY_TEMPLATES = {
  stable: "今天整体波动较平稳，说明你在多数时段保持了可控节奏。",
  highLoad: "你今天不是情绪差，而是消耗偏高，建议今晚优先恢复能量。",
  positive: "你在关键事件后有明显回升，说明你具备良好的调节能力。",
  risk: "检测到高风险表达。请先照顾安全，并考虑联系专业支持。",
};
